version: '2'
services:
  elasticsearch:
    image: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  kibana:
    image: kibana
    links:
      - elasticsearch
    ports:
      - 5601:5601
  fluentd-elasticsearch:
    image: orangemi/fluentd-elasticsearch
    ports:
      - 24224:24224
    links:
      - elasticsearch
    volumes:
      - ./fluentd/data:/fluentd/log
